# Auto-generated by Get-DuplicateDrivers.ps1
# All commands commented by default. Review duplicate-drivers.csv then uncomment by batch.
# Recommended order: 1) GPU  2) Bluetooth  3) Rest
# Reboot after each batch to verify hardware.

# ahflt.inf   keep 10/09/2024 7.56.57.127 (oem65.inf)   delete 08/05/2024 6.54.29.701 (oem1.inf)
# pnputil /delete-driver oem1.inf /uninstall /force

# amdacpbus.inf   keep 08/06/2024 6.0.0.95 (oem39.inf)   delete 05/22/2024 6.0.0.91 (oem25.inf)
# pnputil /delete-driver oem25.inf /uninstall /force

# armourycratecontrolinterface.inf   keep 03/02/2026 1.2.0.2 (oem94.inf)   delete 08/29/2025 1.2.0.0 (oem92.inf)
# pnputil /delete-driver oem92.inf /uninstall /force

# asussci2.inf   keep 04/21/2026 3.1.64.0 (oem5.inf)   delete 03/27/2026 3.1.62.0 (oem42.inf)
# pnputil /delete-driver oem42.inf /uninstall /force

# asussci2.inf   keep 04/21/2026 3.1.64.0 (oem5.inf)   delete 06/17/2025 3.1.45.0 (oem58.inf)
# pnputil /delete-driver oem58.inf /uninstall /force

# netrtwlane601.inf   keep 10/25/2024 6001.15.155.1 (oem83.inf)   delete 05/06/2024 6001.15.152.100 (oem63.inf)
# pnputil /delete-driver oem63.inf /uninstall /force

# nvhda.inf   keep 09/28/2024 1.4.3.2 (oem81.inf)   delete 11/24/2024 1.4.2.6 (oem32.inf)
# pnputil /delete-driver oem32.inf /uninstall /force

# nvhda.inf   keep 09/28/2024 1.4.3.2 (oem81.inf)   delete 01/19/2023 1.3.40.14 (oem33.inf)
# pnputil /delete-driver oem33.inf /uninstall /force

# nvpcf.inf   keep 03/30/2025 32.0.15.7582 (oem89.inf)   delete 11/24/2024 32.0.15.6549 (oem55.inf)
# pnputil /delete-driver oem55.inf /uninstall /force

# nvpcf.inf   keep 03/30/2025 32.0.15.7582 (oem89.inf)   delete 09/20/2023 31.0.15.4570 (oem27.inf)
# pnputil /delete-driver oem27.inf /uninstall /force

# nvpcf.inf   keep 03/30/2025 32.0.15.7582 (oem89.inf)   delete 01/22/2023 31.0.15.3082 (oem26.inf)
# pnputil /delete-driver oem26.inf /uninstall /force

# nvvad.inf   keep 02/28/2024 4.65.0.3 (oem64.inf)   delete 09/22/2022 4.49.0.0 (oem43.inf)
# pnputil /delete-driver oem43.inf /uninstall /force

# prhiddrv.inf   keep 02/20/2024 1.0.16.0 (oem82.inf)   delete 02/24/2023 1.0.11.0 (oem6.inf)
# pnputil /delete-driver oem6.inf /uninstall /force

# rt68cx21x64.inf   keep 11/18/2024 1168.22.1118.2024 (oem80.inf)   delete 12/06/2022 1168.11.1206.2022 (oem73.inf)
# pnputil /delete-driver oem73.inf /uninstall /force

