#!/usr/bin/env python3
"""Parse pnputil /enum-drivers output and find duplicate drivers."""
import re
import csv
from collections import defaultdict

# Read raw output
with open(r"D:\release-foundation\raw_drivers.txt", "r", encoding="utf-8", errors="ignore") as f:
    raw = f.read()

# Split into blocks
blocks = re.split(r'\r?\n\r?\n', raw)
blocks = [b for b in blocks if 'Published Name' in b or '发布名称' in b]

print(f"Found {len(blocks)} driver blocks")

entries = []
for b in blocks:
    h = {}
    for line in b.split('\n'):
        m = re.match(r'^\s*([^:]+?)\s*:\s*(.+?)\s*$', line)
        if m:
            h[m.group(1).strip()] = m.group(2).strip()
    
    published = h.get('Published Name') or h.get('发布名称', '')
    original = h.get('Original Name') or h.get('原始名称', '')
    provider = h.get('Provider Name') or h.get('提供程序名称', '')
    class_name = h.get('Class Name') or h.get('类名称', '')
    version = h.get('Driver Version') or h.get('驱动程序版本', '')
    date = h.get('Driver Date') or h.get('驱动程序日期', '')
    
    if not published:
        continue
    
    # Parse version - extract just the numeric version part (after date if present)
    # Format is typically "MM/DD/YYYY X.X.X.X" or just "X.X.X.X"
    # Split by space and take the last part (version number)
    version_parts_raw = version.split()
    if len(version_parts_raw) >= 2:
        version_num = version_parts_raw[-1]  # Take last part (version number)
    else:
        version_num = version_parts_raw[0] if version_parts_raw else '0'
    
    # Parse version number
    version_clean = re.sub(r'[^\d.]', '', version_num)
    version_parsed_parts = []
    for part in version_clean.split('.'):
        if part:
            version_parsed_parts.append(int(part))
    version_parsed = tuple(version_parsed_parts) if version_parsed_parts else (0,)
    
    entries.append({
        'PublishedName': published,
        'OriginalName': original.lower() if original else '',
        'Provider': provider,
        'Class': class_name,
        'Date': date,
        'Version': version,
        'VersionParsed': version_parsed
    })

print(f"Parsed {len(entries)} driver entries")

# Group by OriginalName (INF file)
groups = defaultdict(list)
for e in entries:
    if e['OriginalName']:
        groups[e['OriginalName']].append(e)

# Find duplicates
exclude_inf = {'ntprint.inf', 'prnms001.inf', 'prnms002.inf', 'prnms003.inf', 'prnms009.inf'}
dup_rows = []

for inf, drivers in groups.items():
    if len(drivers) <= 1:
        continue
    if inf in exclude_inf:
        continue
    
    # Sort by version descending
    drivers.sort(key=lambda x: x['VersionParsed'], reverse=True)
    keep = drivers[0]
    
    for old in drivers[1:]:
        dup_rows.append({
            'INF': inf,
            'DeleteOEM': old['PublishedName'],
            'DeleteVersion': old['Version'],
            'DeleteDate': old['Date'],
            'KeepOEM': keep['PublishedName'],
            'KeepVersion': keep['Version'],
            'KeepDate': keep['Date'],
            'Provider': old['Provider'],
            'Class': old['Class']
        })

print(f"Found {len(dup_rows)} duplicate drivers to delete")

# Write CSV
csv_path = r"D:\release-foundation\duplicate-drivers.csv"
with open(csv_path, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=['INF', 'DeleteOEM', 'DeleteVersion', 'DeleteDate', 
                                           'KeepOEM', 'KeepVersion', 'KeepDate', 'Provider', 'Class'])
    writer.writeheader()
    for row in sorted(dup_rows, key=lambda x: x['INF']):
        writer.writerow(row)

# Write delete script (all commented)
ps_path = r"D:\release-foundation\delete-old-drivers.ps1"
with open(ps_path, 'w', encoding='utf-8') as f:
    f.write("# Auto-generated by Get-DuplicateDrivers.ps1\n")
    f.write("# All commands commented by default. Review duplicate-drivers.csv then uncomment by batch.\n")
    f.write("# Recommended order: 1) GPU  2) Bluetooth  3) Rest\n")
    f.write("# Reboot after each batch to verify hardware.\n\n")
    
    for row in sorted(dup_rows, key=lambda x: x['INF']):
        f.write(f"# {row['INF']}   keep {row['KeepVersion']} ({row['KeepOEM']})   delete {row['DeleteVersion']} ({row['DeleteOEM']})\n")
        f.write(f"# pnputil /delete-driver {row['DeleteOEM']} /uninstall /force\n\n")

print(f"Generated: {csv_path}")
print(f"Generated: {ps_path}")

# Print summary
print("\n=== Summary ===")
print(f"Total drivers scanned: {len(entries)}")
print(f"Unique INF files: {len(groups)}")
print(f"INFs with duplicates: {sum(1 for v in groups.values() if len(v) > 1)}")
print(f"Duplicates to delete: {len(dup_rows)}")

# Print all duplicates
print("\n=== All Duplicates ===")
for row in sorted(dup_rows, key=lambda x: x['INF']):
    print(f"{row['INF']}:")
    print(f"  DELETE: {row['DeleteOEM']} ({row['DeleteVersion']})")
    print(f"  KEEP:   {row['KeepOEM']} ({row['KeepVersion']})")
    print()
