# Run duplicate driver scan and save output to log
$scriptDir = "C:\Users\31524\.claude\skills\win-c-cleaner\scripts"
$outDir = "D:\release-foundation"
$logFile = Join-Path $outDir "driver_scan_log.txt"

"Starting driver scan at $(Get-Date)" | Out-File $logFile

# Import common functions
. "$scriptDir\_Common.ps1"

"Enumerating DriverStore..." | Out-File $logFile -Append

$raw = & pnputil.exe /enum-drivers 2>&1 | Out-String
$blocks = $raw -split "`r?`n`r?`n" | Where-Object { $_ -match 'Published Name|发布名称' }

"Found $($blocks.Count) driver blocks" | Out-File $logFile -Append

$entries = @()
foreach ($b in $blocks) {
    $h = @{}
    foreach ($line in ($b -split "`r?`n")) {
        if ($line -match '^\s*([^:]+?)\s*:\s*(.+?)\s*$') {
            $h[$Matches[1].Trim()] = $Matches[2].Trim()
        }
    }
    $published = $h['Published Name'];          if (-not $published) { $published = $h['发布名称'] }
    $original  = $h['Original Name'];           if (-not $original)  { $original  = $h['原始名称'] }
    $provider  = $h['Provider Name'];           if (-not $provider)  { $provider  = $h['提供程序名称'] }
    $class     = $h['Class Name'];              if (-not $class)     { $class     = $h['类名称'] }
    $version   = $h['Driver Version'];          if (-not $version)   { $version   = $h['驱动程序版本'] }
    $date      = $h['Driver Date'];             if (-not $date)      { $date      = $h['驱动程序日期'] }
    if (-not $published) { continue }
    $entries += [PSCustomObject]@{
        PublishedName = $published
        OriginalName  = if ($original) { $original.ToLowerInvariant() } else { '' }
        Provider      = $provider
        Class         = $class
        Date          = $date
        Version       = $version
        VersionParsed = (try { [Version]($version -replace '[^\d.]','') } catch { [Version]'0.0' })
    }
}

"Parsed $($entries.Count) driver entries" | Out-File $logFile -Append

if (-not $entries) {
    "No driver entries found." | Out-File $logFile -Append
    exit 1
}

# Group by inf and keep newest
$groups = $entries | Group-Object OriginalName | Where-Object { $_.Count -gt 1 }
$excludeInf = @('ntprint.inf','prnms001.inf','prnms002.inf','prnms003.inf','prnms009.inf')

"Found $($groups.Count) INFs with multiple versions" | Out-File $logFile -Append

$dupRows = @()
foreach ($g in $groups) {
    if ($excludeInf -contains $g.Name) { continue }
    $sorted = $g.Group | Sort-Object VersionParsed -Descending
    $keep   = $sorted[0]
    foreach ($old in ($sorted | Select-Object -Skip 1)) {
        $dupRows += [PSCustomObject]@{
            INF           = $g.Name
            DeleteOEM     = $old.PublishedName
            DeleteVersion = $old.Version
            DeleteDate    = $old.Date
            KeepOEM       = $keep.PublishedName
            KeepVersion   = $keep.Version
            KeepDate      = $keep.Date
            Provider      = $old.Provider
            Class         = $old.Class
        }
    }
}

"Found $($dupRows.Count) duplicate drivers to delete" | Out-File $logFile -Append

if (-not $dupRows) {
    "No duplicate drivers found." | Out-File $logFile -Append
    exit 0
}

$csvPath = Join-Path $OutDir 'duplicate-drivers.csv'
$psPath  = Join-Path $OutDir 'delete-old-drivers.ps1'

$dupRows | Sort-Object INF | Export-Csv -LiteralPath $csvPath -Encoding UTF8 -NoTypeInformation

$lines = @(
    '# Auto-generated by Get-DuplicateDrivers.ps1',
    '# All commands commented by default. Review duplicate-drivers.ps1 then uncomment by batch.',
    '# Recommended order: 1) GPU  2) Bluetooth  3) Rest',
    '# Reboot after each batch to verify hardware.',
    ''
)
foreach ($r in ($dupRows | Sort-Object INF)) {
    $lines += "# $($r.INF)   keep $($r.KeepVersion) ($($r.KeepOEM))   delete $($r.DeleteVersion) ($($r.DeleteOEM))"
    $lines += "# pnputil /delete-driver $($r.DeleteOEM) /uninstall /force"
    $lines += ''
}
$lines | Set-Content -LiteralPath $psPath -Encoding UTF8

"Generated: $csvPath" | Out-File $logFile -Append
"Generated: $psPath" | Out-File $logFile -Append
"Done at $(Get-Date)" | Out-File $logFile -Append
